### PR TITLE
Create style.css

### PR DESCRIPTION
**Pull request by Demo-account404**
added a blue background-color

### CODE REVIEW

**Review by Sophies-Creative-hub — CHANGES_REQUESTED** [review]
I just browsed your repo and saw yout forgot to link the stylesheet in the index file

**Comment by Demo-account404** [comment]
sure, I`ll fix it

**Comment by Demo-account404** [comment]
I just added the link

**Review by Sophies-Creative-hub — APPROVED** [review]
Alright, that looks good so far, lets merge this changes

**Pull request merged**
